### ISSUE TITLE
Create NewProject Page

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#117]
Component Path:
pages > NewProject > index.js

User Story:
When I navigate to this page (/projects/new) I would like to see a form that will allow me to do the following:

Add a project name (
Add a project description (Text Area)
Add a project website URL (example heroku app)
Add a source code URL (example github)
Note: the User's id should be passed in as a hidden input field with the name "user" and the value set to the current logged in user's id. 

After I create a project, I would like to be navigated to my project detail page. 

References: 
Refer to ERD for data fields for form:
![image](https://user-images.githubusercontent.com/29959539/115550095-af849e00-a266-11eb-92b0-ff31e8fbde74.png)

Refer to Wireframe Using React-Bootstrap for general page layout and existing login reference design for the new project form.

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by ghost** [comment]
Content in place, moving to open issue
