### ISSUE TITLE
Create EditProject Page

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#118]
Component Path:
pages > EditProject > index.js

User Story:
When I navigate to this page (/projects/new) I would like to see a form with my current data pre-populated, this form will allow me to do the following:

Edit a project name (Input)
Edit a project description (Text Area)
Edit a project website URL (example heroku app)
Edit a source code URL (example github)

Note: the User's id should be added to the requestURL when making a PUT to backend. 

After I create a project, I would like to be navigated to my project detail page. 

References: 
Refer to ERD for data fields for form:
![image](https://user-images.githubusercontent.com/29959539/115550095-af849e00-a266-11eb-92b0-ff31e8fbde74.png)

Refer to Wireframe Using React-Bootstrap for general page layout and existing login reference design for the new project form.

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by stacy125** [comment]
Created EditProject page and form

**Comment by tmarcelojr** [comment]
@stacy125 

• Make sure to follow the assigned path for the component. Your current path is `pages/ProjectPages/EditProject/index.js`.   Expected => `pages/EditProject/index.js`

• current data pre-populated is still needed. Complete setting up for your form.

• Make sure you have logic to save your new changes to actually update the user's info. You will need to do an AJAX call/fetch.

**Comment by stacy125** [comment]
fixed all issues
