### ISSUE TITLE
Create a Wireframe For React Frontend

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#17]
As a client I would like to know the general UX experience for the following views before starting development:

1. Home Page - https://app.diagrams.net/#G1z6eJCEni8TW_IZVsLLbBG34Po4V2smIK
...
5. User Detail Page - https://app.diagrams.net/?libs=general;mockups#G1FgAJ7zz5MsQ0vji0Ur7ANEiO0keuNhRG
6. Login/Signup Page - https://app.diagrams.net/#G1J4uiaGI0Kn7Uc9B9b8DWgcb9rWV2GRyH

Implement Wireframe using one of the following free Wireframing apps:
- Draw.io 
- Miro 
- Mockflow

**Comment by mssugarpop** [comment]
Erika's Todo:
- Delete/Edit Modal
- User Detail Page
- Login/Signup Page

Dimetri's Todo: 
- Home Page
- Project Index Page
- Project Detail Page

**Comment by mssugarpop** [comment]
Login/Signup: https://drive.google.com/file/d/1J4uiaGI0Kn7Uc9B9b8DWgcb9rWV2GRyH/view?usp=sharing
Home: https://drive.google.com/file/d/1z6eJCEni8TW_IZVsLLbBG34Po4V2smIK/view?usp=sharing
User Detail: https://drive.google.com/file/d/1FgAJ7zz5MsQ0vji0Ur7ANEiO0keuNhRG/view?usp=sharing

**Comment by mssugarpop** [comment]
![BLLTNBRD_HOME (2)](https://user-images.githubusercontent.com/77899542/114767140-461c0100-9d35-11eb-861e-3054fd8cad59.jpg)
![BLLTNBRD_userDetail (1)](https://user-images.githubusercontent.com/77899542/114766674-b0807180-9d34-11eb-8e31-be28972bf1a0.jpg)
![BLLTNBRD_loginsignup](https://user-images.githubusercontent.com/77899542/114620383-8a49cb80-9c79-11eb-8258-55e91cd36bc7.jpg)

**Comment by mssugarpop** [comment]
LINK FOR THE GOOGLE SLIDES: https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit?usp=sharing

**Comment by ghost** [comment]
Ticket Closed. First Views In Place
