### ISSUE TITLE
CSS Component Styling 

### ISSUE THREAD

**Issue by Dimetri-Shearwood** [SEI-2121/blltn-brd#26]
Did some research on both React-Bootstrap and React-Materialize. Here are some of the notes I took.
Based on the familiarity with bootstrap, I feel React-Bootstrap would be the best option to go with. They are both really great options and have great prebuilt UI components. However, we haven't worked with Materialize before, and there are a couple steps to setting it up. Bootstrap doesn't need any prior setting up. What do you all think?

### React-Bootstrap

- Pros
    - It's more popular so its easier to find help with online and a wider community to learn from.
    - Many prebuilt UI components
    - Simple even with beginner React or JS skills
    - Grants you more freedom on how you want to do things
- Cons
    - Code bloat-unnecessarily long code
    - Overly detailed component styling. (Unless you do an update to Bootstrap 4.)

### React-Materialize

- Pros
    - Looks good on pretty much any device
    - User friendly for any developer from beginner to pro.
    - Prebuilt designs for different components
    - Simple wording
    - This site has most examples and instructions     [http://react-materialize.github.io/react-materialize/?path=/story/components-navbar--custom-sidenav](http://react-materialize.github.io/react-materialize/?path=/story/components-navbar--custom-sidenav)

- Cons
    - Very opinionated on how elements should behave and look, (however this does help with a consistency that makes every product look great)
    - When making larger files it can get a little bulky.

**Comment by ghost** [comment]
Issue Resolved, React-Bootstrap chosen for FE styling library.
