### ISSUE TITLE
Customize the CRA Starter Files

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#28]
Research how to update the react public folder files 

1. Update Favicon
2. Update the Title property

Example Configuration Options:
https://medium.com/@jenniferdobak/the-public-folder-and-favicons-in-create-react-app-8dc2cc1d492b

Create React App Documentation: 
https://create-react-app.dev/docs/adding-images-fonts-and-files/

**Comment by stacy125** [comment]
update title and logo

**Comment by ghost** [comment]
@stacy125 Did you make a pull request for these changes?
