### ISSUE TITLE
Document Environment Setup

### ISSUE THREAD

**Issue by Underwaterr** [SEI-2121/blltn-brd#3]
Documentation for how to set up a local development environment should be created on this repository's wiki page.

What steps would someone new to the project follow before they can start contributing?

**Comment by bryan-emerson** [comment]
Took a (first?) swing at Environment Setup Doc! 

I'm curious, as I assume the list of dependencies will grow as we continue to build, would it be considered lazy/unnacceptable to say "Look in the pipfile & package.json and install all necessary dependencies?"

**Comment by Underwaterr** [comment]
This is great! 

The "install Python 3.9" part isn't necessary, they'll be installing Python with `pipenv`. Do say that `pipenv` is a requirement, though! 

The `pipenv install` command will automatically install all the dependencies listed in the Pipfile so you don't need to list them as part of the command. Also include the info that they should `cd` into the `back-end` folder before running `pipenv install`. 

Start all sentences with a capital letter!

There is now a `back-end/settings.sql` script that will run the necessary PSQL commands. Replace the SQL instructions with how to run the SQL script. 

For the front-end, just running `npm install` will automatically include all the dependencies, no need to list them out (just like with `pipenv install`)

**Comment by bryan-emerson** [comment]
Implemented prescribed changes. Up for review.

**Comment by Underwaterr** [comment]
Much better!

Please change "CD" to `cd`, and any other file path or code snippets to be inside of `code spans` or 
```
inside of 
code blocks
```
I think that will help a lot with readability!

**Comment by bryan-emerson** [comment]
Alrighty requested changes have been implemented!

**Comment by bryan-emerson** [comment]
corrected .sql file execution with proper command: ```psql -f settings.sql```
