### ISSUE TITLE
Implement a method for State Management for React App

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#34]
Blltn-Brd FE needs a solution for managing global values (see React Context, or Redux). 
Research state management solutions and decide which will be the best solution for the scope of the project. 

Research Resource: 
https://kentcdodds.com/blog/application-state-management-with-react

**Comment by daveeasley550** [comment]
React Context. 
it is the way.
we have spoken.

**Comment by Underwaterr** [comment]
@daveeasley550 plz add relevant info to the wiki!
