### ISSUE TITLE
Create a Heroku Test Environment with Continuous Integration

### ISSUE THREAD

**Issue by Underwaterr** [SEI-2121/blltn-brd#4]
Using GitHub actions, the back-end should be deployed to the Heroku test environment automatically every time someone merges a branch into `main`.

**Comment by bryan-emerson** [comment]
I think i need admin access to the blltn-brd repo/SEI-2121 org? So I can connect the repo to Heroku and set up a team access?

**Comment by Underwaterr** [comment]
With great power comes great responsibility 
![Screen Shot 2021-04-12 at 11 44 52 AM](https://user-images.githubusercontent.com/3163892/114431035-ac155680-9b84-11eb-8ae4-a81041e0beda.png)
