### ISSUE TITLE
Refactor FE App Duplicates 

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#46]
Current Implementation of FE app structure includes duplicate APP components

Refactor Folder Structure so that one App.js file resides in 'Pages>App' Directory (Desired path: 'frontend/blltn-brd/src/pages/App/App.js (or index.js)

- The current content for the App.js file with react/router implemented should be kept.  (currently inside pages>app>App.js)
- Verify that import for Appp in index.js at src root is pointing to ./pages/App/App.js  and displays the react router content

**Comment by ghost** [comment]
Code Merged
