### ISSUE TITLE
Research Image Storage

### ISSUE THREAD

**Issue by LamarSage** [SEI-2121/blltn-brd#47]

**Comment by Underwaterr** [comment]
Updated issue to be about image storage in general, not just for storing screenshots since this app will also include profile pictures, etc.

**Comment by LamarSage** [comment]
Firebase looks like the direction we should go in. The documentation is clear and there are some good up to date tutorials for more guidance. It also has a free option which does exactly what we need.

Documentation: https://firebase.google.com/docs/storage
Tutorial: https://www.youtube.com/watch?v=XeiOnkEI7XI

**Comment by Underwaterr** [comment]
Great, be sure to communicate this with the team (a Slack post should be sufficient) and we should be good to go!
Also, maybe add this info to the wiki if you have not already!
