### ISSUE TITLE
Create Front-End Test Environment in Netlify with Continuous Integration

### ISSUE THREAD

**Issue by Underwaterr** [SEI-2121/blltn-brd#5]
Using GitHub actions, the front-end should be deployed to the test environment automatically every time someone merges a branch into `main`.

**Comment by ghost** [comment]
@Basilisk - As a comment: 
1. Provide Progress Summary
2. Any relevant configuration / deployment Information: 
- Deployment Links
- Anticipated Documentation for configuring CI Pipeline

**Comment by BasiliskOps** [comment]
1. Our project has been successfully published to Netlify with a working production site. However, while `netlify build` succeeds locally, it fails on the Netlify site when attempting to install Pipenv dependencies. Production site yet remains functional.
2. Netlify implements continuous integration via deployments by linking to our GitHub repo. Specifically via the file directory upon which our production build is found.

- Deployed URL: https://twenty-one-env.netlify.app
- Steps taken to achieve continuous integration are as follows:
`npm install netlify-cli -g` —installs Netlify
`netlify login` —authorize repo link w/Netlify 
cd into front-end/blltn-brd/src
`netlify init` —initialize Netlify app
`netlify build` —creates production build of app
` netlify deploy` —creates preview of deployment
`netlify deploy --prod` —final production deployment

**Comment by ghost** [comment]
Closing to Add Deploy Configuration Backlog Ticket
