### ISSUE TITLE
Create a Generic Page Container Component

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#55]
Refer to Wireframe Using React-Bootstrap and reference design for the generic component, this will wrap all content on Pages. Other components will act as children inside. 

Usecases (Pages):

- About
- Login
- Home (Signup)
Component Path:
components > common > Container > index.js

Documentation:
https://react-bootstrap.github.io/layout/grid/

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by stacy125** [comment]
Created a generic page container using react boostrap
