### ISSUE TITLE
Create a Home Page Component 

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#56]
User Story:
When I navigate to this page I would like to see a form that will allow me to sign up and give me information about the site/application. 

After entering my credentials, I would like to be authenticated, and then navigated to my `user detail` page 

Refer to Wireframe Using React-Bootstrap and reference design for the home page. 

Note: Remove current functional component in App.js and replace with new HomePage Component

Component Path:
pages > Home > index.js

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by tmarcelojr** [comment]
Check how you're importing Navbar component. 

```
./src/components/Homepage/index.js
Module not found: Can't resolve '../Common/Navbar' in '/Users/tmfiles/test/blltn-brd/front-end/src/components/Homepage'```

**Comment by ghost** [comment]
Import issues Resolved, we need to add a short 'statement card' component to the homepage, and remove the login component.
