### ISSUE TITLE
Create a Login Page

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#58]
User Story:  
When I navigate to this page I would like to see a form that will allow me to login
After entering my credentials, when I login I would like to be taken to my personal User Detail Page

Component Path:
pages > Login >  index.js

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by ghost** [comment]
Code Merged
