### ISSUE TITLE
Create a User Detail Page

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#59]
User Story:

As a user, I would like to have a public profile page with the following information:

- My name
- My location
- A short introduction/bio written by me
- A profile picture
- Links to my website and other social media
- A list of my projects

If I am logged in and viewing my own user detail I would like to see a user navigation somewhere on the page. This button should navigate my browser to the `'User Edit'` page. 

Component Path:
pages > UserDetail > index.js

Reference Design
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by ghost** [comment]
Initial Routing and Component Completed. 
Remaining Content Outstanding Component Setup and  (Static) Content Testing

**Comment by ghost** [comment]
All component placeholders are created
