### ISSUE TITLE
Create an About Page

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#60]
As a user, when I click the about link in the navigation bar, I would like to learn more about the site and its makers. 

Component Path:
pages > About > index.js

Reference Design for Heading/Navigation. 
https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_1_12

**Comment by ghost** [comment]
The copy on this page can be generated by @Underwaterr and added below.

**Comment by Underwaterr** [comment]
## About `blltn-brd`
Quick: do you have a cross-media strategy for managing emerging social graphs? Do you have a strategy to become cross-media, global? Quick: do you have a web-enabled strategy for handling emerging relationships? At `blltn brd`, we realize how to maximize the micro-interaction. Brave enough to target the commonly-accepted paradigms of the fractal relationship. A company that envisioneers correctly and upgrades the world's capacity to incentivize synergy. What do we enable? Anything and everything. 

### A New Era of Thought Leadership
What does it really mean to cultivate "the portfolio"? Think compelling, 24/7. Think 60/24/7/365. Think virtual. But don't think all three at the same time. `blltn brd` has revamped the conceptualization of experiences. We enable the capability of eyeballs to actualize. Without well-planned niches, micro-interactions are forced to become backwards-thinking. 

### Expect the Unexpected
The markets factor can be summed up in one word: subscriber-defined, cross-platform, real-world. A company that can expedite correctly will (at some undefined point of time in the future) be able to grow fiercely. A company that can architect fiercely will (one day) be able to orchestrate fiercely. What does the term "cyber-bleeding-edge" really mean? Let's find out.

**Comment by ghost** [comment]
Code merged
