### ISSUE TITLE
[Backlog] Implement User Authentication for Django

### ISSUE THREAD

**Issue by Underwaterr** [SEI-2121/blltn-brd#66]
Will involve updating our app's `User` model to extend from Django's `AbstractUser`. People using the app should be able to log in with a username and password and log out. Read more about Django server-side authentication here: https://docs.djangoproject.com/en/3.0/topics/auth/

User authentication will later be used for [authenticating REST routes](https://www.django-rest-framework.org/api-guide/authentication/#json-web-token-authentication) with [Simple JWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/).

**Comment by ghost** [comment]
Issue pending on FE, but user authentication tested and verified by @Underwaterr / @daveeasley550
