### ISSUE TITLE
Create Entity-Relationship Diagram

### ISSUE THREAD

**Issue by Underwaterr** [SEI-2121/blltn-brd#9]
The Entity-Relationship Diagram (ERD) should include the following information:

- What entities exist for this project
- What fields each entity has, including their data type
- What relationships (one-to-many, many-to-many) exist between them

**Comment by LamarSage** [comment]
![USER STORIES project10](https://user-images.githubusercontent.com/80055719/114416303-c5f76f00-9b6d-11eb-8da9-fb17413b0d62.jpg)

**Comment by LamarSage** [comment]
Is this the location we should be posting this at for review?

**Comment by Underwaterr** [comment]
Looking good for a first draft!
Some feedback:
- You never store lists/arrays in a database. How can you represent a "one-to-many" relationship in the diagram?
- "String" is okay, but remember that you need to specify a Django model from this. Specifically, is it a text field? Are they nullable? Here's the Django docs on field types: https://docs.djangoproject.com/en/3.2/ref/models/fields/

**Comment by LamarSage** [comment]
![diagram](https://user-images.githubusercontent.com/80055719/114428218-25a74780-9b79-11eb-99a0-241345acd4b4.jpg)

**Comment by LamarSage** [comment]
Are we looking for something like this?

**Comment by Underwaterr** [comment]
This is great! 
Something that I think will help readability: minimizing the number of circles/boxes by grouping fields together with the models and using arrows to represent the relationships. Here's an example: 
![Database_ER_Diagram_-_New_Page__1_](https://user-images.githubusercontent.com/3163892/114429722-4bd1e500-9b83-11eb-9059-b2510e107bcd.png)

Additionally, your User 'links" field can only be one URL. I think another one-to-many relationship would work better to me! Similarly, the Project's "Screenshots" is type "list", which can't be represented in a database. That's another one-to-many relationship.

**Comment by LamarSage** [comment]
![diagram](https://user-images.githubusercontent.com/80055719/114448234-868e4a00-9b90-11eb-854e-a08048983d47.jpg)

**Comment by LamarSage** [comment]
I believe this meets the intent. However, please let us know what areas, if any, need improving or adjusting. Thank you.

**Comment by Underwaterr** [comment]
So beautiful! We're almost there!
- Both "link" and "screenshot" will be their own models
- The "Users Model" and "Projects Model" boxes are implied, so you can just say the four models (user, project, link and screenshot) are under the "Users" app. 
- Each project will have an associated "User ID" (like you've done) to establish the one-to-many relationship. The users, however, will not have a "Project IDs" field, instead they'll have a field called "Projects" as type "ForeignKey". (You can read more about the ForeignKey type [here](https://pythonprogramming.net/foreign-keys-django-tutorial/).
- We won't store image data in the database. Instead, we'll have images hosted elsewhere and store their URLs. 

I realize this ticket can feel like a bit of a moving target, but it's a very crucial step for this application to get right and we keep getting closer!

**Comment by mssugarpop** [comment]
![ERD project10](https://user-images.githubusercontent.com/77899542/114477882-1224cc80-9bcb-11eb-9f72-75428a3a047f.jpg)

**Comment by Underwaterr** [comment]
🥳

Please add this to [the wiki](https://github.com/SEI-2121/blltn-brd/wiki)!

**Comment by mssugarpop** [comment]
![USER_STORIES_ERD project10_2](https://user-images.githubusercontent.com/77899542/114478943-68930a80-9bcd-11eb-93be-6676898a0271.jpg)
Would this one actually be better, or would the old one suffice?

**Comment by LamarSage** [comment]
![diagram](https://user-images.githubusercontent.com/80055719/114563454-a6734b80-9c2c-11eb-9b82-40a707ea986e.jpg)

**Comment by mssugarpop** [comment]
![USER_STORIES_ERD project10_2 (2)](https://user-images.githubusercontent.com/77899542/114563960-e2fb7300-9c3d-11eb-8c33-80968c036e33.jpg)
With moved arrows. lol

**Comment by ewalker991** [comment]
![USER_STORIES_ERD project10_2 (3)](https://user-images.githubusercontent.com/77899542/114719076-acd4f680-9d04-11eb-9421-6359e6df6bf7.jpg)

**Comment by mssugarpop** [comment]
![USER_STORIES_ERD project10_2 (4)](https://user-images.githubusercontent.com/77899542/114720695-3e913380-9d06-11eb-910a-3f5fe7a3a360.jpg)

**Comment by mssugarpop** [comment]
![USER_STORIES_ERD project10_2 (5)](https://user-images.githubusercontent.com/77899542/114722154-8fedf280-9d07-11eb-8543-eb6524524626.jpg)
?
