### ISSUE TITLE
Create Global Style Sheet for MainApp/style.css

### ISSUE THREAD

**Issue by maker-jws** [SEI-2121/blltn-brd#90]
Include global style overrides for the following style override:

primary color: #009900
border gray: #C8C8C8
accent color: #E6E6E6
search + logout button fill: #006600
exit || close buttons: #868686
EVERYTHING ELSE: white (#FFFFFF) / black (#000000), 
FONT: Helvetica (but feel free to change. This font is Roboto Condensed Bold from GoogleFonts)

Refer to [wireframe](https://docs.google.com/presentation/d/1bKGBzLpykuZHbJWymIxcV_a2LeBlJ2y87fM_IHJSjCc/edit#slide=id.gcd26d78918_0_0) for additional guidance or contact @ewalker991 / @Dimetri-Shearwood .

**Comment by ghost** [comment]
Code Merged
